no changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1050,7 +1050,7 @@ fi
 fi
 
 if test "$THREADLIBS" = no; then
-        { echo "configure: error: Your system doesn't seem to support posix threads. Icecast 1.3 and above won't work without threads support" 1>&2; exit 1; }
+        { echo "configure: error: Your system doesn't seem to support posix threads" 1>&2; exit 1; }
         exit
 fi
 
@@ -1755,7 +1755,7 @@ done
 ac_given_srcdir=$srcdir
 ac_given_INSTALL="$INSTALL"
 
-trap 'rm -fr `echo "Makefile lib/Makefile mpglib/Makefile console/Makefile" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "Makefile lib/Makefile console/Makefile" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -1834,7 +1834,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"Makefile lib/Makefile mpglib/Makefile console/Makefile"}
+CONFIG_FILES=\${CONFIG_FILES-"Makefile lib/Makefile console/Makefile"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
